### ISSUE TITLE
Update data on Thanathorn Juangroongruangkit

### ISSUE THREAD

**Issue by rapee** [codeforthailand/politician-directory#144]
[Thanathorn Juangroongruangkit (Future Forward Party) has become inactive as M.P.](https://twitter.com/Thairath_News/status/1197064815493013505)

Update `is_active` status and add info to `bio`.

```yaml
- id: '177'
  title: นาย
  name: ธนาธร
  lastname: จึงรุ่งเรืองกิจ
  is_mp: true
  is_senator: false
  is_cabinet: false
  party: อนาคตใหม่
  party_group: ฝ่ายค้าน
  mp_type: บัญชีรายชื่อ
  mp_list: '1'
  gender: ชาย
  birthdate: '1978-11-25'
  education: ปริญญาโท
  graduation: 'New York University, US'
  degree: Master of Science in Global Finance
  ex_occupation:
    - นักธุรกิจ
  occupation_group: เอกชน
  asset: 5628118852.01
  debt: 683303.45
  facebook: ''
  twitter: 'https://twitter.com/thanathorn_fwp'
  is_active: false
  bio: ''
```
